//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CrossPlatformWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CrossPlatform), typeof(System.Object));
		L.RegFunction("SendPlatformMsg", SendPlatformMsg);
		L.RegFunction("New", _CreateCrossPlatform);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCrossPlatform(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CrossPlatform obj = new CrossPlatform();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CrossPlatform.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendPlatformMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CrossPlatform obj = (CrossPlatform)ToLua.CheckObject<CrossPlatform>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.SendPlatformMsg(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

