//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CrossPlatformInterfaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CrossPlatformInterface), typeof(System.Object));
		L.RegFunction("SendPlatformMsg", SendPlatformMsg);
		L.RegFunction("New", _CreateCrossPlatformInterface);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateCrossPlatformInterface(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				CrossPlatformInterface obj = new CrossPlatformInterface();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: CrossPlatformInterface.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendPlatformMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CrossPlatformInterface obj = (CrossPlatformInterface)ToLua.CheckObject<CrossPlatformInterface>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.SendPlatformMsg(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, CrossPlatformInterface.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

