//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class IosCrossPlatformWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(IosCrossPlatform), typeof(CrossPlatform));
		L.RegFunction("SendPlatformMsg", SendPlatformMsg);
		L.RegFunction("New", _CreateIosCrossPlatform);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateIosCrossPlatform(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				IosCrossPlatform obj = new IosCrossPlatform();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: IosCrossPlatform.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendPlatformMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			IosCrossPlatform obj = (IosCrossPlatform)ToLua.CheckObject(L, 1, typeof(IosCrossPlatform));
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.SendPlatformMsg(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

