//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_LoadingManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.LoadingManager), typeof(Manager));
		L.RegFunction("Load", Load);
		L.RegFunction("LoadCtrRes", LoadCtrRes);
		L.RegFunction("UnloadAssetBundles", UnloadAssetBundles);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string[] arg1 = ToLua.CheckStringArray(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
			obj.Load(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadCtrRes(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
				obj.LoadCtrRes();
				return 0;
			}
			else if (count == 2)
			{
				LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
				string[] arg0 = ToLua.CheckStringArray(L, 2);
				obj.LoadCtrRes(arg0);
				return 0;
			}
			else if (count == 3)
			{
				LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
				string[] arg0 = ToLua.CheckStringArray(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				obj.LoadCtrRes(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
				string[] arg0 = ToLua.CheckStringArray(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
				obj.LoadCtrRes(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LuaFramework.LoadingManager.LoadCtrRes");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadAssetBundles(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.LoadingManager obj = (LuaFramework.LoadingManager)ToLua.CheckObject<LuaFramework.LoadingManager>(L, 1);
			string[] arg0 = ToLua.CheckStringArray(L, 2);
			obj.UnloadAssetBundles(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

